/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogInInterface;

import databaseConnection.DataAccess;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Elena Ulate Salas
 */
public class MainFrame extends javax.swing.JFrame {
    private final DataAccess dataAccess;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(DataAccess dataAccess) {
        initComponents();
        setLocationRelativeTo(null); // centra el frame
        this.dataAccess = dataAccess;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btLogIn = new javax.swing.JButton();
        btSignUp = new javax.swing.JButton();
        Tittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/App-login-manager-icon.png"))); // NOI18N
        btLogIn.setText("Log In");
        btLogIn.setToolTipText("");
        btLogIn.setFocusable(false);
        btLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogIn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btLogIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogInActionPerformed(evt);
            }
        });

        btSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/signup-icon.png"))); // NOI18N
        btSignUp.setText("Sign Up");
        btSignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSignUp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btSignUp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });

        Tittle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tittle.setText("Welcome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btSignUp)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Tittle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLogIn)
                    .addComponent(btSignUp))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogInActionPerformed
        //llama la ventana de Log In y se oculta la actual
        setVisible(false);
        LogIn log = new LogIn(dataAccess);
        log.setVisible(true);
      
    }//GEN-LAST:event_btLogInActionPerformed

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        //llama la ventana Sign Up y se oculta la actual
        setVisible(false);
        SignUp sign = new SignUp(dataAccess);
        sign.setVisible(true);
    }//GEN-LAST:event_btSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "The program most be started in main class", "Warning", JOptionPane.WARNING_MESSAGE);
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tittle;
    private javax.swing.JButton btLogIn;
    private javax.swing.JButton btSignUp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
