/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShopWebSiteInterface;

import LogInInterface.MainFrame;
import databaseConnection.DataAccess;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Elena Ulate Salas
 */
public class MainMenu extends javax.swing.JFrame {
    private DataAccess dataAccess;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(DataAccess dataAccess) {
        initComponents();
        setLocationRelativeTo(null);
        this.dataAccess = dataAccess;
    }
    public void menuBack(){
        setVisible(false);
        MainFrame mf = new MainFrame(dataAccess);
        mf.setVisible(true);
    }
    public void profile(){
        setVisible(false);
        Profile pf = new Profile(dataAccess);
        pf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btShoppingCart = new javax.swing.JButton();
        btCatalogue = new javax.swing.JButton();
        btProfile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 102, 0));

        btShoppingCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btShoppingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Shopping-cart-icon.png"))); // NOI18N
        btShoppingCart.setText("Shopping Cart");
        btShoppingCart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btShoppingCart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShoppingCartActionPerformed(evt);
            }
        });

        btCatalogue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCatalogue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Actions-view-list-details-icon (1).png"))); // NOI18N
        btCatalogue.setText("Catalogue");
        btCatalogue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCatalogue.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btCatalogue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCatalogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCatalogueActionPerformed(evt);
            }
        });

        btProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profile-icon.png"))); // NOI18N
        btProfile.setText("Profile");
        btProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btCatalogue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btShoppingCart)
                .addGap(31, 31, 31)
                .addComponent(btProfile)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCatalogue)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btShoppingCart)
                        .addComponent(btProfile)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jMenu1.setText("Options");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-back-icon.png"))); // NOI18N
        jMenuItem1.setText("Back to LogIn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/liberar-icono-5826-32.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCatalogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCatalogueActionPerformed
        setVisible(false);
        Shopping sp = new Shopping(dataAccess);
        sp.setVisible(true);
        
    }//GEN-LAST:event_btCatalogueActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         menuBack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShoppingCartActionPerformed
        
    }//GEN-LAST:event_btShoppingCartActionPerformed

    private void btProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfileActionPerformed
        profile();
    }//GEN-LAST:event_btProfileActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "The program most be started in main class", "Warning", JOptionPane.WARNING_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCatalogue;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btShoppingCart;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
